version: "3"

volumes:
  postgres:

services:
  app:
    image: ashno-onepay:latest
    container_name: ashno-onepay-app
    ports:
      - ${SERVER_PORT}:8000
    env_file:
      - .env
    entrypoint: ./ashno-onepay
    networks:
        - ashno-onepay
  postgres:
    image: postgres:16.0-alpine
    restart: always
    container_name: ashno-onepay-postgres
    ports:
      - ${DATABASE_PORT}:5432
#    volumes:
#      - ./ashno-onepay:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
networks:
  ashno-onepay:
    external: true
