package model

type Country struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func GetCountryName(code string) string {
	for _, country := range Countries {
		if country.Code == code {
			return country.Name
		}
	}
	return ""
}

var Countries = []Country{
	{Code: "af", Name: "Afghanistan"},
	{Code: "ax", Name: "Aland Islands"},
	{Code: "al", Name: "Albania"},
	{Code: "dz", Name: "Algeria"},
	{Code: "as", Name: "American Samoa"},
	{Code: "ad", Name: "Andorra"},
	{Code: "ao", Name: "Angola"},
	{Code: "ai", Name: "Anguilla"},
	{Code: "ag", Name: "Antigua and Barbuda"},
	{Code: "ar", Name: "Argentina"},
	{Code: "am", Name: "Armenia"},
	{Code: "aw", Name: "Aruba"},
	{Code: "au", Name: "Australia"},
	{Code: "at", Name: "Austria"},
	{Code: "az", Name: "Azerbaijan"},
	{Code: "bs", Name: "Bahamas"},
	{Code: "bh", Name: "Bahrain"},
	{Code: "bd", Name: "Bangladesh"},
	{Code: "bb", Name: "Barbados"},
	{Code: "by", Name: "Belarus"},
	{Code: "be", Name: "Belgium"},
	{Code: "bz", Name: "Belize"},
	{Code: "bj", Name: "Benin"},
	{Code: "bt", Name: "Bhutan"},
	{Code: "bo", Name: "Bolivia"},
	{Code: "ba", Name: "Bosnia and Herzegovina"},
	{Code: "bw", Name: "Botswana"},
	{Code: "br", Name: "Brazil"},
	{Code: "bn", Name: "Brunei Darussalam"},
	{Code: "bg", Name: "Bulgaria"},
	{Code: "bf", Name: "Burkina Faso"},
	{Code: "bi", Name: "Burundi"},
	{Code: "kh", Name: "Cambodia"},
	{Code: "cm", Name: "Cameroon"},
	{Code: "ca", Name: "Canada"},
	{Code: "cv", Name: "Cape Verde"},
	{Code: "cf", Name: "Central African Republic"},
	{Code: "td", Name: "Chad"},
	{Code: "cl", Name: "Chile"},
	{Code: "cn", Name: "China"},
	{Code: "co", Name: "Colombia"},
	{Code: "km", Name: "Comoros"},
	{Code: "cg", Name: "Congo"},
	{Code: "cd", Name: "Congo (DRC)"},
	{Code: "cr", Name: "Costa Rica"},
	{Code: "ci", Name: "Côte d'Ivoire"},
	{Code: "hr", Name: "Croatia"},
	{Code: "cu", Name: "Cuba"},
	{Code: "cy", Name: "Cyprus"},
	{Code: "cz", Name: "Czech Republic"},
	{Code: "dk", Name: "Denmark"},
	{Code: "dj", Name: "Djibouti"},
	{Code: "dm", Name: "Dominica"},
	{Code: "do", Name: "Dominican Republic"},
	{Code: "ec", Name: "Ecuador"},
	{Code: "eg", Name: "Egypt"},
	{Code: "sv", Name: "El Salvador"},
	{Code: "gq", Name: "Equatorial Guinea"},
	{Code: "er", Name: "Eritrea"},
	{Code: "ee", Name: "Estonia"},
	{Code: "et", Name: "Ethiopia"},
	{Code: "fj", Name: "Fiji"},
	{Code: "fi", Name: "Finland"},
	{Code: "fr", Name: "France"},
	{Code: "ga", Name: "Gabon"},
	{Code: "gm", Name: "Gambia"},
	{Code: "ge", Name: "Georgia"},
	{Code: "de", Name: "Germany"},
	{Code: "gh", Name: "Ghana"},
	{Code: "gr", Name: "Greece"},
	{Code: "gd", Name: "Grenada"},
	{Code: "gt", Name: "Guatemala"},
	{Code: "gn", Name: "Guinea"},
	{Code: "gw", Name: "Guinea-Bissau"},
	{Code: "gy", Name: "Guyana"},
	{Code: "ht", Name: "Haiti"},
	{Code: "hn", Name: "Honduras"},
	{Code: "hk", Name: "Hong Kong"},
	{Code: "hu", Name: "Hungary"},
	{Code: "is", Name: "Iceland"},
	{Code: "in", Name: "India"},
	{Code: "id", Name: "Indonesia"},
	{Code: "ir", Name: "Iran"},
	{Code: "iq", Name: "Iraq"},
	{Code: "ie", Name: "Ireland"},
	{Code: "il", Name: "Israel"},
	{Code: "it", Name: "Italy"},
	{Code: "jm", Name: "Jamaica"},
	{Code: "jp", Name: "Japan"},
	{Code: "jo", Name: "Jordan"},
	{Code: "kz", Name: "Kazakhstan"},
	{Code: "ke", Name: "Kenya"},
	{Code: "ki", Name: "Kiribati"},
	{Code: "kr", Name: "Korea (South)"},
	{Code: "kw", Name: "Kuwait"},
	{Code: "kg", Name: "Kyrgyzstan"},
	{Code: "la", Name: "Laos"},
	{Code: "lv", Name: "Latvia"},
	{Code: "lb", Name: "Lebanon"},
	{Code: "ls", Name: "Lesotho"},
	{Code: "lr", Name: "Liberia"},
	{Code: "ly", Name: "Libya"},
	{Code: "li", Name: "Liechtenstein"},
	{Code: "lt", Name: "Lithuania"},
	{Code: "lu", Name: "Luxembourg"},
	{Code: "mo", Name: "Macao"},
	{Code: "mk", Name: "North Macedonia"},
	{Code: "mg", Name: "Madagascar"},
	{Code: "mw", Name: "Malawi"},
	{Code: "my", Name: "Malaysia"},
	{Code: "mv", Name: "Maldives"},
	{Code: "ml", Name: "Mali"},
	{Code: "mt", Name: "Malta"},
	{Code: "mh", Name: "Marshall Islands"},
	{Code: "mr", Name: "Mauritania"},
	{Code: "mu", Name: "Mauritius"},
	{Code: "mx", Name: "Mexico"},
	{Code: "fm", Name: "Micronesia"},
	{Code: "md", Name: "Moldova"},
	{Code: "mc", Name: "Monaco"},
	{Code: "mn", Name: "Mongolia"},
	{Code: "me", Name: "Montenegro"},
	{Code: "ma", Name: "Morocco"},
	{Code: "mz", Name: "Mozambique"},
	{Code: "mm", Name: "Myanmar"},
	{Code: "na", Name: "Namibia"},
	{Code: "nr", Name: "Nauru"},
	{Code: "np", Name: "Nepal"},
	{Code: "nl", Name: "Netherlands"},
	{Code: "nz", Name: "New Zealand"},
	{Code: "ni", Name: "Nicaragua"},
	{Code: "ne", Name: "Niger"},
	{Code: "ng", Name: "Nigeria"},
	{Code: "no", Name: "Norway"},
	{Code: "om", Name: "Oman"},
	{Code: "pk", Name: "Pakistan"},
	{Code: "pw", Name: "Palau"},
	{Code: "pa", Name: "Panama"},
	{Code: "pg", Name: "Papua New Guinea"},
	{Code: "py", Name: "Paraguay"},
	{Code: "pe", Name: "Peru"},
	{Code: "ph", Name: "Philippines"},
	{Code: "pl", Name: "Poland"},
	{Code: "pt", Name: "Portugal"},
	{Code: "qa", Name: "Qatar"},
	{Code: "ro", Name: "Romania"},
	{Code: "ru", Name: "Russia"},
	{Code: "rw", Name: "Rwanda"},
	{Code: "kn", Name: "Saint Kitts and Nevis"},
	{Code: "lc", Name: "Saint Lucia"},
	{Code: "vc", Name: "Saint Vincent and the Grenadines"},
	{Code: "ws", Name: "Samoa"},
	{Code: "sm", Name: "San Marino"},
	{Code: "st", Name: "Sao Tome and Principe"},
	{Code: "sa", Name: "Saudi Arabia"},
	{Code: "sn", Name: "Senegal"},
	{Code: "rs", Name: "Serbia"},
	{Code: "sc", Name: "Seychelles"},
	{Code: "sl", Name: "Sierra Leone"},
	{Code: "sg", Name: "Singapore"},
	{Code: "sk", Name: "Slovakia"},
	{Code: "si", Name: "Slovenia"},
	{Code: "sb", Name: "Solomon Islands"},
	{Code: "so", Name: "Somalia"},
	{Code: "za", Name: "South Africa"},
	{Code: "es", Name: "Spain"},
	{Code: "lk", Name: "Sri Lanka"},
	{Code: "sd", Name: "Sudan"},
	{Code: "sr", Name: "Suriname"},
	{Code: "se", Name: "Sweden"},
	{Code: "ch", Name: "Switzerland"},
	{Code: "sy", Name: "Syria"},
	{Code: "tw", Name: "Taiwan"},
	{Code: "tj", Name: "Tajikistan"},
	{Code: "tz", Name: "Tanzania"},
	{Code: "th", Name: "Thailand"},
	{Code: "tl", Name: "Timor-Leste"},
	{Code: "tg", Name: "Togo"},
	{Code: "to", Name: "Tonga"},
	{Code: "tt", Name: "Trinidad and Tobago"},
	{Code: "tn", Name: "Tunisia"},
	{Code: "tr", Name: "Turkey"},
	{Code: "tm", Name: "Turkmenistan"},
	{Code: "tv", Name: "Tuvalu"},
	{Code: "ug", Name: "Uganda"},
	{Code: "ua", Name: "Ukraine"},
	{Code: "ae", Name: "United Arab Emirates"},
	{Code: "gb", Name: "United Kingdom"},
	{Code: "us", Name: "United States"},
	{Code: "uy", Name: "Uruguay"},
	{Code: "uz", Name: "Uzbekistan"},
	{Code: "vu", Name: "Vanuatu"},
	{Code: "va", Name: "Vatican City"},
	{Code: "ve", Name: "Venezuela"},
	{Code: "vn", Name: "Vietnam"},
	{Code: "ye", Name: "Yemen"},
	{Code: "zm", Name: "Zambia"},
	{Code: "zw", Name: "Zimbabwe"},
}
